NEWS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from newspaper.views import CustomLogin
urlpatterns = [
    path("admin/", admin.site.urls),
    path("summernote/", include("django_summernote.urls")),
    path("api/v1/", include("api.urls")),
    path("", include("newspaper.urls")),
    path("accounts/login/", CustomLogin.as_view(), name="login"),
    # path("accounts/login/", LoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework import routers

from api import views

router = routers.DefaultRouter()
router.register("users", views.UserViewSet)
router.register("groups", views.GroupViewSet)
router.register("tags", views.TagViewSet)
router.register("categories", views.CategoryViewSet)
router.register("posts", views.PostViewSet)
router.register("contact-us", views.ContactViewSet)
router.register("newsletter", views.NewsLetterViewSet)
# router.register("comments/<int:post_id>", views.CommentViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path("", include(router.urls)),
    path(
        "draft-list/",
        views.DraftListViewSet.as_view(),
        name="draft-list",
    ),
    path(
        "post-publish/",
        views.PostPublishViewSet.as_view(),
        name="post-publish",
    ),
    path(
        "top-categories/",
        views.TopCategoriesListViewSet.as_view(),
        name="top-categories",
    ),
    path(
        "post-by-category/<int:cat_id>/",
        views.PostByCategoryListViewSet.as_view(),
        name="top-by-category",
    ),
    path(
        "post-by-tag/<int:tag_id>/",
        views.PostByTagListViewSet.as_view(),
        name="post-by-tag",
    ),
    path(
        "post/<int:post_id>/comments/",
        views.PostCommentViewSet.as_view(),
        name="post-comment",
    ),
    path(
        "api-auth/",
        include("rest_framework.urls", namespace="rest_framework"),
    ),
]

newspaper/models.py
from django.db import models


class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True  # does not create table for TimeStampModel


class Category(TimeStampModel):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tag(TimeStampModel):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(TimeStampModel):
    STATUS_CHOICES = (
        ("published", "Published"),
        ("unpublished", "Un-published"),
    )
    title = models.CharField(max_length=255)
    content = models.TextField()
    featured_image = models.ImageField(upload_to="post_images/%Y/%m/%d", blank=False)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    published_at = models.DateTimeField(null=True, blank=True)
    views_count = models.PositiveBigIntegerField(default=0)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="unpublished"
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    # Fat model and thin views
    @property
    def latest_comments(self):
        comments = Comment.objects.filter(post=self).order_by("-created_at")
        return comments


class NewsLetter(TimeStampModel):
    email = models.EmailField()

    def __str__(self):
        return self.email


class Contact(TimeStampModel):
    subject = models.CharField(max_length=200)
    message = models.TextField()
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.subject
    
    class Meta:
        ordering = ['created_at']
        # db_table = 'newsletter'


class Comment(TimeStampModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.message[:70]

templates/aznews/about.html
{% extends "aznews/base.html" %}
{% load static %}

{% block content %}
  <main>
    <!-- About US Start -->
    <div class="about-area">
      <div class="container">
        <!-- Hot Aimated News Tittle-->
        <div class="row">
          <div class="col-lg-12">
            <div class="trending-tittle">
              <strong>Trending now</strong>
              <!-- <p>Rem ipsum dolor sit amet, consectetur adipisicing elit.</p> -->
              <div class="trending-animated">
                <ul id="js-news" class="js-hidden">
                  <li class="news-item">Bangladesh dolor sit amet, consectetur adipisicing elit.</li>
                  <li class="news-item">Spondon IT sit amet, consectetur.......</li>
                  <li class="news-item">Rem ipsum dolor sit amet, consectetur adipisicing elit.</li>
                </ul>
              </div>
 
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-8">
            <!-- Trending Tittle -->
            <div class="about-right mb-90">
              <div class="about-img">
                <img src="{% static 'assets/img/post/about_heor.jpg' %}" alt="">
              </div>
              <div class="section-tittle mb-30 pt-30">
                <h3>About Us</h3>
              </div>
              <div class="about-prea">
                <p class="about-pera1 mb-25">
                  Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch.
                </p>
                <p class="about-pera1 mb-25">
                  Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch.
                </p>
                <p class="about-pera1 mb-25">
                  My hero when I was a kid was my mom. Same for everyone I knew. Moms are untouchable. They’re elegant, smart, beautiful, kind…everything we want to be. At 29 years old, my favorite compliment is being told that I look like my mom. Seeing myself in her image, like this daughter up top, makes me so proud of how far I’ve come, and so thankful for where I come from.
                  the refractor telescope uses a convex lens to focus the light on the eyepiece.
                  The reflector telescope has a concave lens which means it bends in. It uses mirrors to focus the image that you eventually see.
                  Collimation is a term for how well tuned the telescope is to give you a good clear image of what you are looking at. You want your telescope to have good collimation so you are not getting a false image of the celestial body.
                  Aperture is a fancy word for how big the lens of your telescope is. But it’s an important word because the aperture of the lens is the key to how powerful your telescope is. Magnification has nothing to do with it, its all in the aperture.
                  Focuser is the housing that keeps the eyepiece of the telescope, or what you will look through, in place. The focuser has to be stable and in good repair for you to have an image you can rely on.
                  Mount and Wedge. Both of these terms refer to the tripod your telescope sits on. The mount is the actual tripod and the wedge is the device that lets you attach the telescope to the mount.
                  Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch.
                </p>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <!-- Section Tittle -->
            <div class="section-tittle mb-40">
              <h3>Follow Us</h3>
            </div>
            <!-- Flow Socail -->
            <div class="single-follow mb-45">
              <div class="single-box">
                <div class="follow-us d-flex align-items-center">
                  <div class="follow-social">
                    <a href="#">
                      <img src="{% static 'assets/img/news/icon-fb.png' %}" alt="">
                    </a>
                  </div>
                  <div class="follow-count">
                    <span>8,045</span>
                    <p>Fans</p>
                  </div>
                </div>
                <div class="follow-us d-flex align-items-center">
                  <div class="follow-social">
                    <a href="#">
                      <img src="{% static 'assets/img/news/icon-tw.png' %}" alt="">
                    </a>
                  </div>
                  <div class="follow-count">
                    <span>8,045</span>
                    <p>Fans</p>
                  </div>
                </div>
                <div class="follow-us d-flex align-items-center">
                  <div class="follow-social">
                    <a href="#">
                      <img src="{% static 'assets/img/news/icon-ins.png' %}" alt="">
                    </a>
                  </div>
                  <div class="follow-count">
                    <span>8,045</span>
                    <p>Fans</p>
                  </div>
                </div>
                <div class="follow-us d-flex align-items-center">
                  <div class="follow-social">
                    <a href="#">
                      <img src="{% static 'assets/img/news/icon-yo.png' %}" alt="">
                    </a>
                  </div>
                  <div class="follow-count">
                    <span>8,045</span>
                    <p>Fans</p>
                  </div>
                </div>
              </div>
            </div>
            <!-- New Poster -->
            <div class="news-poster d-none d-lg-block">
              <img src="{% static 'assets/img/news/news_card.jpg' %}" alt="">
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About US End -->
  </main>
{% endblock content %}

templates/aznews/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>News HTML-5 Template</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="manifest" href="site.webmanifest" />
    <link rel="shortcut icon"
          type="image/x-icon"
          href="{% static 'assets/img/favicon.ico' %}"/>

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <link rel="stylesheet"
          href="{% static 'assets/css/owl.carousel.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/ticker-style.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}" />
    <link rel="stylesheet"
          href="{% static 'assets/css/fontawesome-all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
  </head>

  <body>
    <!-- Preloader Start -->
    <!-- <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="assets/img/logo/logo.png" alt="">
                </div>
            </div>
        </div>
    </div> -->
    <!-- Preloader Start -->
    {% include "aznews/header/header.html" %}

    {% block content %}
    {% endblock content %}
 
    {% include "aznews/footer/footer.html" %}

    <!-- JS here -->

    <!-- All JS Custom Plugins Link Here here -->
    <script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/slick.min.js' %}"></script>
    <!-- Date Picker -->
    <script src="{% static 'assets/js/gijgo.min.js' %}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/animated.headline.js' %}"></script>
    <script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- Breaking New Pluging -->
    <script src="{% static 'assets/js/jquery.ticker.js' %}"></script>
    <script src="{% static 'assets/js/site.js' %}"></script>

    <!-- Scrollup, nice-select, sticky -->
    <script src="{% static 'assets/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.sticky.js' %}"></script>

    <!-- contact js -->
    <script src="{% static 'assets/js/contact.js' %}"></script>
    <script src="{% static 'assets/js/jquery.form.js' %}"></script>
    <script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'assets/js/mail-script.js' %}"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="{% static 'assets/js/plugins.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script>
      $("#news_letter_side_form").submit(function(e) {
          e.preventDefault(); // do not reload the browser
          let serializedData = $(this).serialize();
          $.ajax({
              type: "POST",
              data: serializedData,
              url: "{% url 'newsletter' %}",
              success: function(response) {
                  $("#newsletter_letter_message").append(
                      `
                                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                                          <strong>${response.message}</strong>
                                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div>
                                      `
                  )
              },
              error: function(response) {
                  $("#newsletter_letter_message").append(
                      `
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                          <strong>${response.message}</strong>
                                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div>
                                      `
                  )
              }
          })
      })

      $("#news_letter_bottom_form").submit(function(e) {
          e.preventDefault(); // do not reload the browser
          let serializedData = $(this).serialize();
          console.log(serializedData)
          $.ajax({
              type: "POST",
              data: serializedData,
              url: "{% url 'newsletter' %}",
              success: function(response) {
                  $("#newsletter_letter_bottom_message").append(
                      `
                                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                                          <strong>${response.message}</strong>
                                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div>
                                      `
                  )
              },
              error: function(response) {
                  $("#newsletter_letter_bottom_message").append(
                      `
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                          <strong>${response.message}</strong>
                                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div>
                                      `
                  )
              }
          })
      })
    </script>
    {% block extra_script %}
 
    {% endblock extra_script %}
  </body>
</html>

templates/aznews/contact.html
{% extends "aznews/base.html" %}

{% block content %}
  <!-- ================ contact section start ================= -->
  <section class="contact-section">
    <div class="container">
      <div class="row">
        <div class="col-12">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show"
                   role="alert">
                <strong>{{ message }}</strong>
                {% if form.errors and form.non_field_errors %}{{ form.non_field_errors }}{% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
          {% endif %}
          
          <h2 class="contact-title">Get in Touch</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact contact_form"
                action=""
                method="post"
                id="contactForm"
                novalidate="novalidate">
            {% csrf_token %}
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  <input class="form-control"
                         name="subject"
                         id="subject"
                         type="text"
                         onfocus="this.placeholder = ''"
                         onblur="this.placeholder = 'Enter Subject'"
                         placeholder="Enter Subject">
                  {{ form.subject.errors }}
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  <textarea class="form-control w-100"
                            name="message"
                            id="message"
                            cols="30"
                            rows="9"
                            onfocus="this.placeholder = ''"
                            onblur="this.placeholder = 'Enter Message'"
                            placeholder=" Enter Message"></textarea>
                  {{ form.message.errors }}
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control valid"
                         name="name"
                         id="name"
                         type="text"
                         onfocus="this.placeholder = ''"
                         onblur="this.placeholder = 'Enter your name'"
                         placeholder="Enter your name">
                  {{ form.name.errors }}
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control valid"
                         name="email"
                         id="email"
                         type="email"
                         onfocus="this.placeholder = ''"
                         onblur="this.placeholder = 'Enter email address'"
                         placeholder="Email">
                  {{ form.email.errors }}
                </div>
              </div>
 
            </div>
            <div class="form-group mt-3">
              <button type="submit" class="button button-contactForm boxed-btn">Send</button>
            </div>
          </form>
        </div>
        <div class="col-lg-3 offset-lg-1">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Buttonwood, California.</h3>
              <p>Rosemead, CA 91770</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>+1 253 565 2365</h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>support@colorlib.com</h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ================ contact section end ================= -->
{% endblock content %}

templates/aznews/detail.html
{% extends "aznews/base.html" %}

{% block content %}
  <!--================Blog Area =================-->
  <section class="blog_area single-post-area section-padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 posts-list">
          {% include "aznews/main/detail/left/post_detail.html" %}
          {% include "aznews/main/detail/left/nav.html" %}
          {% include "aznews/main/detail/left/author.html" %}
          {% include "aznews/main/detail/left/comment_list.html" %}
          {% include "aznews/main/detail/left/comment_form.html" %}
        </div>
        <div class="col-lg-4">
          <div class="blog_right_sidebar">
            {% include "aznews/main/detail/right/search.html" %}
            {% include "aznews/main/detail/right/category.html" %}
            {% include "aznews/main/detail/right/popular.html" %}
            {% include "aznews/main/detail/right/tag.html" %}
            {% include "aznews/main/detail/right/newsletter.html" %}
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================ Blog Area end =================-->
{% endblock content %}

templates/aznews/home.html
{% extends "aznews/base.html" %}

{% block content %}
  {% include "aznews/main/main.html" %}
{% endblock content %}

templates/aznews/list.html
{% extends "aznews/base.html" %}

{% block content %}
  <!--================Blog Area =================-->
  <section class="blog_area section-padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mb-5 mb-lg-0">
          <div class="blog_left_sidebar">
            {% for post in posts %}
              <article class="blog_item">
                <div class="blog_item_img">
                  <img class="card-img rounded-0"
                       src="{{ post.featured_image.url }}"
                       alt="{{ post.title }}">
                  <a href="#" class="blog_item_date">
                    <h3>{{ post.published_at|date:"j" }}</h3>
                    <p>{{ post.published_at|date:"M" }}</p>
                  </a>
                </div>
                <div class="blog_details">
                  <a class="d-inline-block" href="{% url 'post-detail' post.pk %}">
                    <h2>{{ post.title }}</h2>
                  </a>
                  <p>{{ post.content|striptags|truncatechars:177 }}</p>
                  <ul class="blog-info-link">
                    <li>
                      <a href="#"><i class="fa fa-user"></i>{{ post.tag.all|join:", " }}</a>
                    </li>
                    <li>
                      <a href="#"><i class="fa fa-comments"></i> {{ post.latest_comments.count }} Comments</a>
                    </li>
                  </ul>
                </div>
              </article>
            {% endfor %}
            {% include "aznews/pagination.html" %}
          </div>
        </div>
        <div class="col-lg-4">
          <div class="blog_right_sidebar">
            {% include "aznews/main/detail/right/search.html" %}
            {% include "aznews/main/detail/right/category.html" %}
            {% include "aznews/main/detail/right/popular.html" %}
            {% include "aznews/main/detail/right/tag.html" %}
            {% include "aznews/main/detail/right/newsletter.html" %}
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================Blog Area =================-->
{% endblock content %}

templates/aznews/login.html
{% extends "news_admin/base.html" %}

{% block content %}
  {% if form.non_field_errors %}
    <p class="text-danger">
      {{ form.non_field_errors }}
    </p>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="username" class="form-label">Username</label>
      <input type="text"
             class="form-control"
             id="username"
             placeholder="Enter your username..."
             name="username">
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password"
             class="form-control"
             id="password"
             placeholder="Enter your password..."
             name="password">
    </div>
    <button type="submit" class="btn btn-success">Login</button>
  </form>
{% endblock content %}

templates/aznews/pagination.html
{% if is_paginated or page_obj.has_other_pages %}
  <nav class="blog-pagination justify-content-center d-flex">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?page={{ page_obj.previous_page_number }}"
             class="page-link pagination_number"
             aria-label="Previous">
            <i class="ti-angle-left"></i>
          </a>
        </li>
      {% endif %}

      {% for i in page_obj.paginator.page_range %}
        <li class="page-item {% if page_obj.number == i %}active{% endif %} ">
          <a href="?page={{ i }}" class="page-link pagination_number">{{ i }}</a>
        </li>
      {% endfor %}
 
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?page={{ page_obj.next_page_number }}"
             class="page-link pagination_number"
             aria-label="Next">
            <i class="ti-angle-right"></i>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/aznews/search_list.html
{% extends "aznews/base.html" %}

{% block content %}
  <!--================Blog Area =================-->
  <section class="blog_area section-padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mb-5 mb-lg-0">
          <div class="blog_left_sidebar">
            {% for post in page_obj %}
              <article class="blog_item">
                <div class="blog_item_img">
                  <img class="card-img rounded-0"
                       src="{{ post.featured_image.url }}"
                       alt="{{ post.title }}">
                  <a href="#" class="blog_item_date">
                    <h3>{{ post.published_at|date:"j" }}</h3>
                    <p>{{ post.published_at|date:"M" }}</p>
                  </a>
                </div>
                <div class="blog_details">
                  <a class="d-inline-block" href="{% url 'post-detail' post.pk %}">
                    <h2>{{ post.title }}</h2>
                  </a>
                  <p>{{ post.content|striptags|truncatechars:177 }}</p>
                  <ul class="blog-info-link">
                    <li>
                      <a href="#"><i class="fa fa-user"></i>{{ post.tag.all|join:", " }}</a>
                    </li>
                    <li>
                      <a href="#"><i class="fa fa-comments"></i> {{ post.latest_comments.count }} Comments</a>
                    </li>
                  </ul>
                </div>
              </article>
            {% endfor %}
            {% include "aznews/pagination.html" %}
          </div>
        </div>
        <div class="col-lg-4">
          <div class="blog_right_sidebar">
            {% include "aznews/main/detail/right/search.html" %}
            {% include "aznews/main/detail/right/category.html" %}
            {% include "aznews/main/detail/right/popular.html" %}
            {% include "aznews/main/detail/right/tag.html" %}
            {% include "aznews/main/detail/right/newsletter.html" %}
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================Blog Area =================-->
{% endblock content %}

{% block extra_script %}
  <script>
    $('.pagination_number').click(function(e) {
        e.preventDefault(); // prevent default action 
        let current_url = window.location.href.split("?")[0]
        let params = new URL(document.location).searchParams;
        let query = params.get("query")
        let href = $(this).attr("href");
        let new_url = `${current_url}${href}&query=${query}`;
        window.location.replace(new_url);
    })
  </script>
{% endblock extra_script %}